global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi' #애플리케이션 메트릭 수집
    static_configs:
      - targets: ['fastapi-app:5001']
  - job_name: 'node' #시스템 메트릭 수집 !
    static_configs:
      - targets: ['node-exporter:9100']